name: xephas
description: This is Cephas Brian, a designer and developer of experiences

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.2
  ionicons: ^0.1.2

  # state
  flutter_riverpod: ^1.0.4

  # fonsts
  google_fonts: ^3.0.1

  # routing
  go_router: ^4.1.0

  # ui
  flextras: ^0.0.2
  responsive_sizer: ^3.1.0
  dotted_border: ^2.0.0+2

  # images
  flutter_svg: ^1.1.1+1
  cached_network_image: ^3.2.3

  # links
  url_launcher: ^6.1.5
  share_plus: ^4.0.10
  whatsapp_unilink: ^2.0.1+1
  flutter_form_builder: ^7.7.0
  flutter_localizations:
    sdk: flutter
  form_builder_validators: ^8.4.0
  fluttertoast: ^8.1.2

#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - icons/
