name: xephas
description: This is Cephas Brian, a designer and developer of experiences

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  google_fonts: ^3.0.1
  go_router: ^4.1.0
  ionicons: ^0.1.2
  flextras: ^0.0.2
  responsive_sizer: ^3.1.0
  flutter_svg: ^1.1.1+1
  url_launcher: ^6.1.5
  share_plus: ^4.0.10
  whatsapp_unilink: ^2.0.1+1
  dotted_border: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - icons/
